### PR TITLE
feat: implement serde for dkg types

### PR DESCRIPTION
**Pull request by dignifiedquire**
This is missing support for bls12_377 as that has no serde support yet. Also simplified some `Clone` bounds.

### CODE REVIEW

**Comment by kobigurk** [comment]
We need no_std compatibility - can you make sure this compiles for WASM? I think serde needs a special import for no_std.

**Comment by dignifiedquire** [comment]
do you need no std or wasm compat? this crate is using things like Vec, so it is not really no std atm

**Comment by kobigurk** [comment]
> do you need no std or wasm compat? this crate is using things like Vec, so it is not really no std atm
> […](#)
> On 13. Apr 2020, 08:49 +0200, Kobi Gurkan ***@***.***>, wrote: We need no_std compatibility - can you make sure this compiles for WASM? I think serde needs a special import for no_std. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yeah, more correctly we need WASM compatibility. A lot of std stuff doesn't directly work on WASM, but yeah, some things do. We're currently working on adding WASM examples for the library (https://github.com/celo-org/celo-threshold-bls-rs/pull/8), so we'll be able to make sure things don't break going forward.

**Comment by gakonst** [comment]
Closing this as it was made part of https://github.com/celo-org/celo-threshold-bls-rs/pull/12. Thank you @dignifiedquire!

**Pull request closed without merging**
